name: sentry_client
version: 4.2.1
description: The Dart library for sending data to the Sentry server.
authors:
  - Ivan Evsikov <ivan.evsikov@team.wrike.com>
homepage: https://github.com/wrike/sentry_client
environment:
  sdk: '>=2.0.0-dev.36.0 <3.0.0'

dependencies:
  uuid: ^1.0.0

dev_dependencies:
  test: ^1.3.0
#  coverage: '>=0.7.9 <2.0.0'
  mockito: ^3.0.0
  quiver: ^2.0.0
#  dart_dev: '>=1.7.2'
#  dart_style: ^1.0.7
  build_runner: '>=0.9.1 <2.0.0'
  build_test: '>=0.10.2 <2.0.0'
  build_web_compilers: '>=0.4.0 <2.0.0'

#transformers:
#- test/pub_serve:
#    $include: test/**_test{.*,}.dart

